# Generated by Django 3.2.4 on 2021-07-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
    ]
