# Generated by Django 3.2.4 on 2021-07-04 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_up_votes',
            field=models.ManyToManyField(blank=True, related_name='user_up_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
